services:
  - type: web
    name: label-converter
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
